apiVersion: actions.github.com/v1beta1
kind: HorizontalRunnerAutoscaler
metadata:
  name: repo-runner-autoscaler
  namespace: actions-runner-system
spec:
  scaleUpTriggers:
    - githubEvent:
        workflow_job:
          types:
            - queued
  scaleDownDelaySecondsAfterEachJob: 180
  minReplicas: 0
  maxReplicas: 5
  scaleTargetRef:
    kind: RunnerDeployment
    name: repo-runner
  template:
    spec:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2
          memory: 4Gi