apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 15m
  path: ../../infrastructure/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: secrets-store-csi-driver
      namespace: kube-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: actions-runner-controller
      namespace: actions-runner-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs 
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: infra-controllers
  path: ../../infrastructure/staging 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true