apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 15m
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.41.0"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: arc-config
      valuesKey: values.yaml
      optional: true
  values:
    authSecret:
      create: false
      name: controller-manager-github-pat
    controller:
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
    workloadIdentity:
      enabled: true
      serviceAccountAnnotations:
        azure.workload.identity/client-id: "" 
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: controller-manager