blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/ianoflynn/terraform-private-aks-cluster/security/policy
    about: Please report security vulnerabilities via the security policy.
  - name: Questions / Support
    url: https://github.com/ianoflynn/terraform-private-aks-cluster/discussions
    about: Ask questions and find answers in Discussions.
