apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.5.2"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: csi-config
      valuesKey: values.yaml
      optional: true
  values:
    syncSecret: true
    enableSecretRotation: true
    rotationPollInterval: 2m
    securityContext:  
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 512Mi
    workloadIdentity:
      enabled: true
      issuerUrl: ${oidcIssuerUrl}